
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.mortiusweaponryredux.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.item.Items;
import net.minecraft.world.item.Item;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import net.mcreator.mortiusweaponryredux.procedures.QuiverPropertyValueProviderProcedure;
import net.mcreator.mortiusweaponryredux.procedures.NetheriteBowPropertyProcedure;
import net.mcreator.mortiusweaponryredux.procedures.IronBowPropertyValueProviderProcedure;
import net.mcreator.mortiusweaponryredux.procedures.DiamondBowPropertyProcedure;
import net.mcreator.mortiusweaponryredux.procedures.CopperBowPropertyProcedure;
import net.mcreator.mortiusweaponryredux.procedures.AutoBowPropertyProcedure;
import net.mcreator.mortiusweaponryredux.item.WoodenWarhammerItem;
import net.mcreator.mortiusweaponryredux.item.WoodenTwinBladeItem;
import net.mcreator.mortiusweaponryredux.item.WoodenThrowingKnifeItem;
import net.mcreator.mortiusweaponryredux.item.WoodenSpearItem;
import net.mcreator.mortiusweaponryredux.item.WoodenSickleItem;
import net.mcreator.mortiusweaponryredux.item.WoodenScytheItem;
import net.mcreator.mortiusweaponryredux.item.WoodenSchiavonaItem;
import net.mcreator.mortiusweaponryredux.item.WoodenSaberItem;
import net.mcreator.mortiusweaponryredux.item.WoodenRapierItem;
import net.mcreator.mortiusweaponryredux.item.WoodenQuarterstaffItem;
import net.mcreator.mortiusweaponryredux.item.WoodenPikeItem;
import net.mcreator.mortiusweaponryredux.item.WoodenParryingDaggerItem;
import net.mcreator.mortiusweaponryredux.item.WoodenOdachiItem;
import net.mcreator.mortiusweaponryredux.item.WoodenMesserItem;
import net.mcreator.mortiusweaponryredux.item.WoodenMaceItem;
import net.mcreator.mortiusweaponryredux.item.WoodenLongswordItem;
import net.mcreator.mortiusweaponryredux.item.WoodenLanceItem;
import net.mcreator.mortiusweaponryredux.item.WoodenKhopeshItem;
import net.mcreator.mortiusweaponryredux.item.WoodenKatanaItem;
import net.mcreator.mortiusweaponryredux.item.WoodenJavelinItem;
import net.mcreator.mortiusweaponryredux.item.WoodenHalberdItem;
import net.mcreator.mortiusweaponryredux.item.WoodenGreatswordItem;
import net.mcreator.mortiusweaponryredux.item.WoodenGlaiveItem;
import net.mcreator.mortiusweaponryredux.item.WoodenGladiusItem;
import net.mcreator.mortiusweaponryredux.item.WoodenFlailItem;
import net.mcreator.mortiusweaponryredux.item.WoodenFalchionItem;
import net.mcreator.mortiusweaponryredux.item.WoodenExecutionerSwordItem;
import net.mcreator.mortiusweaponryredux.item.WoodenDaggerItem;
import net.mcreator.mortiusweaponryredux.item.WoodenChakramItem;
import net.mcreator.mortiusweaponryredux.item.WoodenBattleAxeItem;
import net.mcreator.mortiusweaponryredux.item.WeaponPoleItem;
import net.mcreator.mortiusweaponryredux.item.WeaponHandleItem;
import net.mcreator.mortiusweaponryredux.item.WaterFlaskItem;
import net.mcreator.mortiusweaponryredux.item.TraitorsGreedItem;
import net.mcreator.mortiusweaponryredux.item.ThousandCutsItem;
import net.mcreator.mortiusweaponryredux.item.ThickFlaskItem;
import net.mcreator.mortiusweaponryredux.item.SunFuryItem;
import net.mcreator.mortiusweaponryredux.item.StoneWarhammerItem;
import net.mcreator.mortiusweaponryredux.item.StoneTwinBladeItem;
import net.mcreator.mortiusweaponryredux.item.StoneThrowingKnifeItem;
import net.mcreator.mortiusweaponryredux.item.StoneSpearItem;
import net.mcreator.mortiusweaponryredux.item.StoneSickleItem;
import net.mcreator.mortiusweaponryredux.item.StoneScytheItem;
import net.mcreator.mortiusweaponryredux.item.StoneSchiavonaItem;
import net.mcreator.mortiusweaponryredux.item.StoneSaberItem;
import net.mcreator.mortiusweaponryredux.item.StoneRapierItem;
import net.mcreator.mortiusweaponryredux.item.StoneQuarterstaffItem;
import net.mcreator.mortiusweaponryredux.item.StonePikeItem;
import net.mcreator.mortiusweaponryredux.item.StoneParryingDaggerItem;
import net.mcreator.mortiusweaponryredux.item.StoneOdachiItem;
import net.mcreator.mortiusweaponryredux.item.StoneMesserItem;
import net.mcreator.mortiusweaponryredux.item.StoneMaceItem;
import net.mcreator.mortiusweaponryredux.item.StoneLongswordItem;
import net.mcreator.mortiusweaponryredux.item.StoneLanceItem;
import net.mcreator.mortiusweaponryredux.item.StoneKhopeshItem;
import net.mcreator.mortiusweaponryredux.item.StoneKatanaItem;
import net.mcreator.mortiusweaponryredux.item.StoneJavelinItem;
import net.mcreator.mortiusweaponryredux.item.StoneHalberdItem;
import net.mcreator.mortiusweaponryredux.item.StoneGreatswordItem;
import net.mcreator.mortiusweaponryredux.item.StoneGlaiveItem;
import net.mcreator.mortiusweaponryredux.item.StoneGladiusItem;
import net.mcreator.mortiusweaponryredux.item.StoneFlailItem;
import net.mcreator.mortiusweaponryredux.item.StoneFalchionItem;
import net.mcreator.mortiusweaponryredux.item.StoneExecutionerSwordItem;
import net.mcreator.mortiusweaponryredux.item.StoneDaggerItem;
import net.mcreator.mortiusweaponryredux.item.StoneChakramItem;
import net.mcreator.mortiusweaponryredux.item.StoneBattleAxeItem;
import net.mcreator.mortiusweaponryredux.item.SteelWarhammerItem;
import net.mcreator.mortiusweaponryredux.item.SteelTwinBladeItem;
import net.mcreator.mortiusweaponryredux.item.SteelSpearItem;
import net.mcreator.mortiusweaponryredux.item.SteelSickleItem;
import net.mcreator.mortiusweaponryredux.item.SteelScytheItem;
import net.mcreator.mortiusweaponryredux.item.SteelSchiavonaItem;
import net.mcreator.mortiusweaponryredux.item.SteelSaberItem;
import net.mcreator.mortiusweaponryredux.item.SteelRapierItem;
import net.mcreator.mortiusweaponryredux.item.SteelQuarterstaffItem;
import net.mcreator.mortiusweaponryredux.item.SteelPikeItem;
import net.mcreator.mortiusweaponryredux.item.SteelParryingDaggerItem;
import net.mcreator.mortiusweaponryredux.item.SteelOdachiItem;
import net.mcreator.mortiusweaponryredux.item.SteelMesserItem;
import net.mcreator.mortiusweaponryredux.item.SteelMaceItem;
import net.mcreator.mortiusweaponryredux.item.SteelLongswordItem;
import net.mcreator.mortiusweaponryredux.item.SteelLanceItem;
import net.mcreator.mortiusweaponryredux.item.SteelKhopeshItem;
import net.mcreator.mortiusweaponryredux.item.SteelKatanaItem;
import net.mcreator.mortiusweaponryredux.item.SteelJavelinItem;
import net.mcreator.mortiusweaponryredux.item.SteelHalberdItem;
import net.mcreator.mortiusweaponryredux.item.SteelGreatswordItem;
import net.mcreator.mortiusweaponryredux.item.SteelGlaiveItem;
import net.mcreator.mortiusweaponryredux.item.SteelGladiusItem;
import net.mcreator.mortiusweaponryredux.item.SteelFlailItem;
import net.mcreator.mortiusweaponryredux.item.SteelFalchionItem;
import net.mcreator.mortiusweaponryredux.item.SteelExecutionerSwordItem;
import net.mcreator.mortiusweaponryredux.item.SteelDaggerItem;
import net.mcreator.mortiusweaponryredux.item.SteelBattleAxeItem;
import net.mcreator.mortiusweaponryredux.item.SpikedShieldItem;
import net.mcreator.mortiusweaponryredux.item.SpikedMusketBallItem;
import net.mcreator.mortiusweaponryredux.item.SoulEaterItem;
import net.mcreator.mortiusweaponryredux.item.SilverWarhammerItem;
import net.mcreator.mortiusweaponryredux.item.SilverTwinBladeItem;
import net.mcreator.mortiusweaponryredux.item.SilverSpearItem;
import net.mcreator.mortiusweaponryredux.item.SilverSickleItem;
import net.mcreator.mortiusweaponryredux.item.SilverScytheItem;
import net.mcreator.mortiusweaponryredux.item.SilverSchiavonaItem;
import net.mcreator.mortiusweaponryredux.item.SilverSaberItem;
import net.mcreator.mortiusweaponryredux.item.SilverRapierItem;
import net.mcreator.mortiusweaponryredux.item.SilverQuarterstaffItem;
import net.mcreator.mortiusweaponryredux.item.SilverPikeItem;
import net.mcreator.mortiusweaponryredux.item.SilverParryingDaggerItem;
import net.mcreator.mortiusweaponryredux.item.SilverOdachiItem;
import net.mcreator.mortiusweaponryredux.item.SilverMesserItem;
import net.mcreator.mortiusweaponryredux.item.SilverMaceItem;
import net.mcreator.mortiusweaponryredux.item.SilverLongswordItem;
import net.mcreator.mortiusweaponryredux.item.SilverLanceItem;
import net.mcreator.mortiusweaponryredux.item.SilverKhopeshItem;
import net.mcreator.mortiusweaponryredux.item.SilverKatanaItem;
import net.mcreator.mortiusweaponryredux.item.SilverJavelinItem;
import net.mcreator.mortiusweaponryredux.item.SilverHalberdItem;
import net.mcreator.mortiusweaponryredux.item.SilverGreatswordItem;
import net.mcreator.mortiusweaponryredux.item.SilverGlaiveItem;
import net.mcreator.mortiusweaponryredux.item.SilverGladiusItem;
import net.mcreator.mortiusweaponryredux.item.SilverFlailItem;
import net.mcreator.mortiusweaponryredux.item.SilverFalchionItem;
import net.mcreator.mortiusweaponryredux.item.SilverExecutionerSwordItem;
import net.mcreator.mortiusweaponryredux.item.SilverDaggerItem;
import net.mcreator.mortiusweaponryredux.item.SilverBattleAxeItem;
import net.mcreator.mortiusweaponryredux.item.ShortBarrelItem;
import net.mcreator.mortiusweaponryredux.item.SeraphItem;
import net.mcreator.mortiusweaponryredux.item.SealedShieldItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldWarhammerItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldTwinBladeItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldSpearItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldSickleItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldScytheItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldSchiavonaItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldSaberItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldRapierItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldQuarterstaffItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldPikeItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldParryingDaggerItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldOdachiItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldMesserItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldMaceItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldLongswordItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldLanceItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldKhopeshItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldKatanaItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldJavelinItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldHalberdItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldGreatswordItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldGlaiveItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldGladiusItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldFlailItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldFalchionItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldExecutionerSwordItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldDaggerItem;
import net.mcreator.mortiusweaponryredux.item.RoseGoldBattleAxeItem;
import net.mcreator.mortiusweaponryredux.item.RetributionItem;
import net.mcreator.mortiusweaponryredux.item.RamrodItem;
import net.mcreator.mortiusweaponryredux.item.QuiverItem;
import net.mcreator.mortiusweaponryredux.item.PhantomMusketBallItem;
import net.mcreator.mortiusweaponryredux.item.OrnateQuiverItem;
import net.mcreator.mortiusweaponryredux.item.OpposingWindsItem;
import net.mcreator.mortiusweaponryredux.item.ObsidianKnifeItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteWarhammerItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteTwinBladeItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteThrowingKnifeItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteSpearItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteSickleItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteShieldItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteScytheItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteSchiavonaItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteSaberItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteRapierItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteQuiverItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteQuarterstaffItem;
import net.mcreator.mortiusweaponryredux.item.NetheritePikeItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteParryingDaggerItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteOdachiItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteMesserItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteMaceItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteLongswordItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteLanceItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteKhopeshItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteKatanaItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteJavelinItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteHalberdItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteGreatswordItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteGlaiveItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteGladiusItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteFlailItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteFalchionItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteExecutionerSwordItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteDaggerItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteChakramItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteBowItem;
import net.mcreator.mortiusweaponryredux.item.NetheriteBattleAxeItem;
import net.mcreator.mortiusweaponryredux.item.NecrostaffItem;
import net.mcreator.mortiusweaponryredux.item.NaturesJudgementItem;
import net.mcreator.mortiusweaponryredux.item.MusketItem;
import net.mcreator.mortiusweaponryredux.item.MusketBallPouchItem;
import net.mcreator.mortiusweaponryredux.item.MusketBallPieceItem;
import net.mcreator.mortiusweaponryredux.item.MusketBallItem;
import net.mcreator.mortiusweaponryredux.item.MundaneFlaskItem;
import net.mcreator.mortiusweaponryredux.item.LongBarrelItem;
import net.mcreator.mortiusweaponryredux.item.LivingShieldItem;
import net.mcreator.mortiusweaponryredux.item.KrakenHunterItem;
import net.mcreator.mortiusweaponryredux.item.IronWarhammerItem;
import net.mcreator.mortiusweaponryredux.item.IronTwinBladeItem;
import net.mcreator.mortiusweaponryredux.item.IronThrowingKnifeItem;
import net.mcreator.mortiusweaponryredux.item.IronSpearItem;
import net.mcreator.mortiusweaponryredux.item.IronSickleItem;
import net.mcreator.mortiusweaponryredux.item.IronScytheItem;
import net.mcreator.mortiusweaponryredux.item.IronSchiavonaItem;
import net.mcreator.mortiusweaponryredux.item.IronSaberItem;
import net.mcreator.mortiusweaponryredux.item.IronRapierItem;
import net.mcreator.mortiusweaponryredux.item.IronQuarterstaffItem;
import net.mcreator.mortiusweaponryredux.item.IronPikeItem;
import net.mcreator.mortiusweaponryredux.item.IronParryingDaggerItem;
import net.mcreator.mortiusweaponryredux.item.IronOdachiItem;
import net.mcreator.mortiusweaponryredux.item.IronMesserItem;
import net.mcreator.mortiusweaponryredux.item.IronMaceItem;
import net.mcreator.mortiusweaponryredux.item.IronLongswordItem;
import net.mcreator.mortiusweaponryredux.item.IronLanceItem;
import net.mcreator.mortiusweaponryredux.item.IronKhopeshItem;
import net.mcreator.mortiusweaponryredux.item.IronKatanaItem;
import net.mcreator.mortiusweaponryredux.item.IronJavelinItem;
import net.mcreator.mortiusweaponryredux.item.IronHalberdItem;
import net.mcreator.mortiusweaponryredux.item.IronGreatswordItem;
import net.mcreator.mortiusweaponryredux.item.IronGlaiveItem;
import net.mcreator.mortiusweaponryredux.item.IronGladiusItem;
import net.mcreator.mortiusweaponryredux.item.IronFlailItem;
import net.mcreator.mortiusweaponryredux.item.IronFalchionItem;
import net.mcreator.mortiusweaponryredux.item.IronExecutionerSwordItem;
import net.mcreator.mortiusweaponryredux.item.IronDaggerItem;
import net.mcreator.mortiusweaponryredux.item.IronChakramItem;
import net.mcreator.mortiusweaponryredux.item.IronBowItem;
import net.mcreator.mortiusweaponryredux.item.IronBattleAxeItem;
import net.mcreator.mortiusweaponryredux.item.HellfireMusketBallItem;
import net.mcreator.mortiusweaponryredux.item.HeavyMusketBallItem;
import net.mcreator.mortiusweaponryredux.item.HeadsmanItem;
import net.mcreator.mortiusweaponryredux.item.GoldenWarhammerItem;
import net.mcreator.mortiusweaponryredux.item.GoldenTwinBladeItem;
import net.mcreator.mortiusweaponryredux.item.GoldenThrowingKnifeItem;
import net.mcreator.mortiusweaponryredux.item.GoldenSpearItem;
import net.mcreator.mortiusweaponryredux.item.GoldenSickleItem;
import net.mcreator.mortiusweaponryredux.item.GoldenScytheItem;
import net.mcreator.mortiusweaponryredux.item.GoldenSchiavonaItem;
import net.mcreator.mortiusweaponryredux.item.GoldenSaberItem;
import net.mcreator.mortiusweaponryredux.item.GoldenRapierItem;
import net.mcreator.mortiusweaponryredux.item.GoldenQuarterstaffItem;
import net.mcreator.mortiusweaponryredux.item.GoldenPikeItem;
import net.mcreator.mortiusweaponryredux.item.GoldenParryingDaggerItem;
import net.mcreator.mortiusweaponryredux.item.GoldenOdachiItem;
import net.mcreator.mortiusweaponryredux.item.GoldenMesserItem;
import net.mcreator.mortiusweaponryredux.item.GoldenMaceItem;
import net.mcreator.mortiusweaponryredux.item.GoldenLongswordItem;
import net.mcreator.mortiusweaponryredux.item.GoldenLanceItem;
import net.mcreator.mortiusweaponryredux.item.GoldenKhopeshItem;
import net.mcreator.mortiusweaponryredux.item.GoldenKatanaItem;
import net.mcreator.mortiusweaponryredux.item.GoldenJavelinItem;
import net.mcreator.mortiusweaponryredux.item.GoldenHalberdItem;
import net.mcreator.mortiusweaponryredux.item.GoldenGreatswordItem;
import net.mcreator.mortiusweaponryredux.item.GoldenGlaiveItem;
import net.mcreator.mortiusweaponryredux.item.GoldenGladiusItem;
import net.mcreator.mortiusweaponryredux.item.GoldenFlailItem;
import net.mcreator.mortiusweaponryredux.item.GoldenFalchionItem;
import net.mcreator.mortiusweaponryredux.item.GoldenExecutionerSwordItem;
import net.mcreator.mortiusweaponryredux.item.GoldenDaggerItem;
import net.mcreator.mortiusweaponryredux.item.GoldenChakramItem;
import net.mcreator.mortiusweaponryredux.item.GoldenBattleAxeItem;
import net.mcreator.mortiusweaponryredux.item.GlassFlaskItem;
import net.mcreator.mortiusweaponryredux.item.FrostmawItem;
import net.mcreator.mortiusweaponryredux.item.FlintlockPistolItem;
import net.mcreator.mortiusweaponryredux.item.FlintlockMechanismItem;
import net.mcreator.mortiusweaponryredux.item.FlaskOfWitherItem;
import net.mcreator.mortiusweaponryredux.item.FlaskOfWeaknessItem;
import net.mcreator.mortiusweaponryredux.item.FlaskOfVolatileConcoctionItem;
import net.mcreator.mortiusweaponryredux.item.FlaskOfSoulFireItem;
import net.mcreator.mortiusweaponryredux.item.FlaskOfSlownessItem;
import net.mcreator.mortiusweaponryredux.item.FlaskOfSlowFallingItem;
import net.mcreator.mortiusweaponryredux.item.FlaskOfPoisonItem;
import net.mcreator.mortiusweaponryredux.item.FlaskOfLightningItem;
import net.mcreator.mortiusweaponryredux.item.FlaskOfLevitationItem;
import net.mcreator.mortiusweaponryredux.item.FlaskOfGunpowderItem;
import net.mcreator.mortiusweaponryredux.item.FlaskOfGlowingItem;
import net.mcreator.mortiusweaponryredux.item.FlaskOfFireItem;
import net.mcreator.mortiusweaponryredux.item.FlaskOfBlindnessItem;
import net.mcreator.mortiusweaponryredux.item.FieryMusketBallItem;
import net.mcreator.mortiusweaponryredux.item.ExplosiveShieldItem;
import net.mcreator.mortiusweaponryredux.item.ExplosiveMusketBallItem;
import net.mcreator.mortiusweaponryredux.item.EstocItem;
import net.mcreator.mortiusweaponryredux.item.EnderShieldItem;
import net.mcreator.mortiusweaponryredux.item.EnderBallItem;
import net.mcreator.mortiusweaponryredux.item.EchoingSickleItem;
import net.mcreator.mortiusweaponryredux.item.DiamondWarhammerItem;
import net.mcreator.mortiusweaponryredux.item.DiamondTwinBladeItem;
import net.mcreator.mortiusweaponryredux.item.DiamondThrowingKnifeItem;
import net.mcreator.mortiusweaponryredux.item.DiamondSpearItem;
import net.mcreator.mortiusweaponryredux.item.DiamondSickleItem;
import net.mcreator.mortiusweaponryredux.item.DiamondShieldItem;
import net.mcreator.mortiusweaponryredux.item.DiamondScytheItem;
import net.mcreator.mortiusweaponryredux.item.DiamondSchiavonaItem;
import net.mcreator.mortiusweaponryredux.item.DiamondSaberItem;
import net.mcreator.mortiusweaponryredux.item.DiamondRapierItem;
import net.mcreator.mortiusweaponryredux.item.DiamondQuarterstaffItem;
import net.mcreator.mortiusweaponryredux.item.DiamondPikeItem;
import net.mcreator.mortiusweaponryredux.item.DiamondParryingDaggerItem;
import net.mcreator.mortiusweaponryredux.item.DiamondOdachiItem;
import net.mcreator.mortiusweaponryredux.item.DiamondMesserItem;
import net.mcreator.mortiusweaponryredux.item.DiamondMaceItem;
import net.mcreator.mortiusweaponryredux.item.DiamondLongswordItem;
import net.mcreator.mortiusweaponryredux.item.DiamondLanceItem;
import net.mcreator.mortiusweaponryredux.item.DiamondKhopeshItem;
import net.mcreator.mortiusweaponryredux.item.DiamondKatanaItem;
import net.mcreator.mortiusweaponryredux.item.DiamondJavelinItem;
import net.mcreator.mortiusweaponryredux.item.DiamondHalberdItem;
import net.mcreator.mortiusweaponryredux.item.DiamondGreatswordItem;
import net.mcreator.mortiusweaponryredux.item.DiamondGlaiveItem;
import net.mcreator.mortiusweaponryredux.item.DiamondGladiusItem;
import net.mcreator.mortiusweaponryredux.item.DiamondFlailItem;
import net.mcreator.mortiusweaponryredux.item.DiamondFalchionItem;
import net.mcreator.mortiusweaponryredux.item.DiamondExecutionerSwordItem;
import net.mcreator.mortiusweaponryredux.item.DiamondDaggerItem;
import net.mcreator.mortiusweaponryredux.item.DiamondChakramItem;
import net.mcreator.mortiusweaponryredux.item.DiamondBucklerItem;
import net.mcreator.mortiusweaponryredux.item.DiamondBowItem;
import net.mcreator.mortiusweaponryredux.item.DiamondBattleAxeItem;
import net.mcreator.mortiusweaponryredux.item.DeathScytheItem;
import net.mcreator.mortiusweaponryredux.item.DPSMeterItem;
import net.mcreator.mortiusweaponryredux.item.CrystallizedMusketBallItem;
import net.mcreator.mortiusweaponryredux.item.CrystalPieceItem;
import net.mcreator.mortiusweaponryredux.item.CrackedMusketBallItem;
import net.mcreator.mortiusweaponryredux.item.CopperWarhammerItem;
import net.mcreator.mortiusweaponryredux.item.CopperTwinBladeItem;
import net.mcreator.mortiusweaponryredux.item.CopperSpearItem;
import net.mcreator.mortiusweaponryredux.item.CopperSickleItem;
import net.mcreator.mortiusweaponryredux.item.CopperScytheItem;
import net.mcreator.mortiusweaponryredux.item.CopperSchiavonaItem;
import net.mcreator.mortiusweaponryredux.item.CopperSaberItem;
import net.mcreator.mortiusweaponryredux.item.CopperRapierItem;
import net.mcreator.mortiusweaponryredux.item.CopperQuarterstaffItem;
import net.mcreator.mortiusweaponryredux.item.CopperPikeItem;
import net.mcreator.mortiusweaponryredux.item.CopperParryingDaggerItem;
import net.mcreator.mortiusweaponryredux.item.CopperOdachiItem;
import net.mcreator.mortiusweaponryredux.item.CopperMesserItem;
import net.mcreator.mortiusweaponryredux.item.CopperMaceItem;
import net.mcreator.mortiusweaponryredux.item.CopperLongswordItem;
import net.mcreator.mortiusweaponryredux.item.CopperLanceItem;
import net.mcreator.mortiusweaponryredux.item.CopperKhopeshItem;
import net.mcreator.mortiusweaponryredux.item.CopperKatanaItem;
import net.mcreator.mortiusweaponryredux.item.CopperJavelinItem;
import net.mcreator.mortiusweaponryredux.item.CopperHalberdItem;
import net.mcreator.mortiusweaponryredux.item.CopperGreatswordItem;
import net.mcreator.mortiusweaponryredux.item.CopperGlaiveItem;
import net.mcreator.mortiusweaponryredux.item.CopperGladiusItem;
import net.mcreator.mortiusweaponryredux.item.CopperFlailItem;
import net.mcreator.mortiusweaponryredux.item.CopperFalchionItem;
import net.mcreator.mortiusweaponryredux.item.CopperExecutionerSwordItem;
import net.mcreator.mortiusweaponryredux.item.CopperDaggerItem;
import net.mcreator.mortiusweaponryredux.item.CopperBowItem;
import net.mcreator.mortiusweaponryredux.item.CopperBattleAxeItem;
import net.mcreator.mortiusweaponryredux.item.CatastropheItem;
import net.mcreator.mortiusweaponryredux.item.BucklerItem;
import net.mcreator.mortiusweaponryredux.item.BronzeWarhammerItem;
import net.mcreator.mortiusweaponryredux.item.BronzeTwinBladeItem;
import net.mcreator.mortiusweaponryredux.item.BronzeSpearItem;
import net.mcreator.mortiusweaponryredux.item.BronzeSickleItem;
import net.mcreator.mortiusweaponryredux.item.BronzeScytheItem;
import net.mcreator.mortiusweaponryredux.item.BronzeSchiavonaItem;
import net.mcreator.mortiusweaponryredux.item.BronzeSaberItem;
import net.mcreator.mortiusweaponryredux.item.BronzeRapierItem;
import net.mcreator.mortiusweaponryredux.item.BronzeQuarterstaffItem;
import net.mcreator.mortiusweaponryredux.item.BronzePikeItem;
import net.mcreator.mortiusweaponryredux.item.BronzeParryingDaggerItem;
import net.mcreator.mortiusweaponryredux.item.BronzeOdachiItem;
import net.mcreator.mortiusweaponryredux.item.BronzeMesserItem;
import net.mcreator.mortiusweaponryredux.item.BronzeMaceItem;
import net.mcreator.mortiusweaponryredux.item.BronzeLongswordItem;
import net.mcreator.mortiusweaponryredux.item.BronzeLanceItem;
import net.mcreator.mortiusweaponryredux.item.BronzeKhopeshItem;
import net.mcreator.mortiusweaponryredux.item.BronzeKatanaItem;
import net.mcreator.mortiusweaponryredux.item.BronzeJavelinItem;
import net.mcreator.mortiusweaponryredux.item.BronzeHalberdItem;
import net.mcreator.mortiusweaponryredux.item.BronzeGreatswordItem;
import net.mcreator.mortiusweaponryredux.item.BronzeGlaiveItem;
import net.mcreator.mortiusweaponryredux.item.BronzeGladiusItem;
import net.mcreator.mortiusweaponryredux.item.BronzeFlailItem;
import net.mcreator.mortiusweaponryredux.item.BronzeFalchionItem;
import net.mcreator.mortiusweaponryredux.item.BronzeExecutionerSwordItem;
import net.mcreator.mortiusweaponryredux.item.BronzeDaggerItem;
import net.mcreator.mortiusweaponryredux.item.BronzeBattleAxeItem;
import net.mcreator.mortiusweaponryredux.item.BlunderbussItem;
import net.mcreator.mortiusweaponryredux.item.BlunderbussBarrelItem;
import net.mcreator.mortiusweaponryredux.item.BlazeRodPoleItem;
import net.mcreator.mortiusweaponryredux.item.BlazeRodHandleItem;
import net.mcreator.mortiusweaponryredux.item.AwkwardFlaskItem;
import net.mcreator.mortiusweaponryredux.item.AutoBowItem;
import net.mcreator.mortiusweaponryredux.item.AssaultShieldItem;
import net.mcreator.mortiusweaponryredux.MortiusWeaponryReduxMod;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class MortiusWeaponryReduxModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MortiusWeaponryReduxMod.MODID);
	public static final RegistryObject<Item> WOODEN_GLADIUS = REGISTRY.register("wooden_gladius", () -> new WoodenGladiusItem());
	public static final RegistryObject<Item> STONE_GLADIUS = REGISTRY.register("stone_gladius", () -> new StoneGladiusItem());
	public static final RegistryObject<Item> GOLDEN_GLADIUS = REGISTRY.register("golden_gladius", () -> new GoldenGladiusItem());
	public static final RegistryObject<Item> IRON_GLADIUS = REGISTRY.register("iron_gladius", () -> new IronGladiusItem());
	public static final RegistryObject<Item> DIAMOND_GLADIUS = REGISTRY.register("diamond_gladius", () -> new DiamondGladiusItem());
	public static final RegistryObject<Item> NETHERITE_GLADIUS = REGISTRY.register("netherite_gladius", () -> new NetheriteGladiusItem());
	public static final RegistryObject<Item> WEAPON_HANDLE = REGISTRY.register("weapon_handle", () -> new WeaponHandleItem());
	public static final RegistryObject<Item> WOODEN_DAGGER = REGISTRY.register("wooden_dagger", () -> new WoodenDaggerItem());
	public static final RegistryObject<Item> STONE_DAGGER = REGISTRY.register("stone_dagger", () -> new StoneDaggerItem());
	public static final RegistryObject<Item> GOLDEN_DAGGER = REGISTRY.register("golden_dagger", () -> new GoldenDaggerItem());
	public static final RegistryObject<Item> IRON_DAGGER = REGISTRY.register("iron_dagger", () -> new IronDaggerItem());
	public static final RegistryObject<Item> DIAMOND_DAGGER = REGISTRY.register("diamond_dagger", () -> new DiamondDaggerItem());
	public static final RegistryObject<Item> NETHERITE_DAGGER = REGISTRY.register("netherite_dagger", () -> new NetheriteDaggerItem());
	public static final RegistryObject<Item> WOODEN_RAPIER = REGISTRY.register("wooden_rapier", () -> new WoodenRapierItem());
	public static final RegistryObject<Item> STONE_RAPIER = REGISTRY.register("stone_rapier", () -> new StoneRapierItem());
	public static final RegistryObject<Item> GOLDEN_RAPIER = REGISTRY.register("golden_rapier", () -> new GoldenRapierItem());
	public static final RegistryObject<Item> IRON_RAPIER = REGISTRY.register("iron_rapier", () -> new IronRapierItem());
	public static final RegistryObject<Item> DIAMOND_RAPIER = REGISTRY.register("diamond_rapier", () -> new DiamondRapierItem());
	public static final RegistryObject<Item> NETHERITE_RAPIER = REGISTRY.register("netherite_rapier", () -> new NetheriteRapierItem());
	public static final RegistryObject<Item> WOODEN_KHOPESH = REGISTRY.register("wooden_khopesh", () -> new WoodenKhopeshItem());
	public static final RegistryObject<Item> STONE_KHOPESH = REGISTRY.register("stone_khopesh", () -> new StoneKhopeshItem());
	public static final RegistryObject<Item> GOLDEN_KHOPESH = REGISTRY.register("golden_khopesh", () -> new GoldenKhopeshItem());
	public static final RegistryObject<Item> IRON_KHOPESH = REGISTRY.register("iron_khopesh", () -> new IronKhopeshItem());
	public static final RegistryObject<Item> DIAMOND_KHOPESH = REGISTRY.register("diamond_khopesh", () -> new DiamondKhopeshItem());
	public static final RegistryObject<Item> NETHERITE_KHOPESH = REGISTRY.register("netherite_khopesh", () -> new NetheriteKhopeshItem());
	public static final RegistryObject<Item> WOODEN_HALBERD = REGISTRY.register("wooden_halberd", () -> new WoodenHalberdItem());
	public static final RegistryObject<Item> STONE_HALBERD = REGISTRY.register("stone_halberd", () -> new StoneHalberdItem());
	public static final RegistryObject<Item> GOLDEN_HALBERD = REGISTRY.register("golden_halberd", () -> new GoldenHalberdItem());
	public static final RegistryObject<Item> IRON_HALBERD = REGISTRY.register("iron_halberd", () -> new IronHalberdItem());
	public static final RegistryObject<Item> DIAMOND_HALBERD = REGISTRY.register("diamond_halberd", () -> new DiamondHalberdItem());
	public static final RegistryObject<Item> NETHERITE_HALBERD = REGISTRY.register("netherite_halberd", () -> new NetheriteHalberdItem());
	public static final RegistryObject<Item> WEAPON_POLE = REGISTRY.register("weapon_pole", () -> new WeaponPoleItem());
	public static final RegistryObject<Item> WOODEN_WARHAMMER = REGISTRY.register("wooden_warhammer", () -> new WoodenWarhammerItem());
	public static final RegistryObject<Item> STONE_WARHAMMER = REGISTRY.register("stone_warhammer", () -> new StoneWarhammerItem());
	public static final RegistryObject<Item> GOLDEN_WARHAMMER = REGISTRY.register("golden_warhammer", () -> new GoldenWarhammerItem());
	public static final RegistryObject<Item> IRON_WARHAMMER = REGISTRY.register("iron_warhammer", () -> new IronWarhammerItem());
	public static final RegistryObject<Item> DIAMOND_WARHAMMER = REGISTRY.register("diamond_warhammer", () -> new DiamondWarhammerItem());
	public static final RegistryObject<Item> NETHERITE_WARHAMMER = REGISTRY.register("netherite_warhammer", () -> new NetheriteWarhammerItem());
	public static final RegistryObject<Item> WOODEN_SICKLE = REGISTRY.register("wooden_sickle", () -> new WoodenSickleItem());
	public static final RegistryObject<Item> STONE_SICKLE = REGISTRY.register("stone_sickle", () -> new StoneSickleItem());
	public static final RegistryObject<Item> GOLDEN_SICKLE = REGISTRY.register("golden_sickle", () -> new GoldenSickleItem());
	public static final RegistryObject<Item> IRON_SICKLE = REGISTRY.register("iron_sickle", () -> new IronSickleItem());
	public static final RegistryObject<Item> DIAMOND_SICKLE = REGISTRY.register("diamond_sickle", () -> new DiamondSickleItem());
	public static final RegistryObject<Item> NETHERITE_SICKLE = REGISTRY.register("netherite_sickle", () -> new NetheriteSickleItem());
	public static final RegistryObject<Item> WOODEN_MACE = REGISTRY.register("wooden_mace", () -> new WoodenMaceItem());
	public static final RegistryObject<Item> STONE_MACE = REGISTRY.register("stone_mace", () -> new StoneMaceItem());
	public static final RegistryObject<Item> GOLDEN_MACE = REGISTRY.register("golden_mace", () -> new GoldenMaceItem());
	public static final RegistryObject<Item> IRON_MACE = REGISTRY.register("iron_mace", () -> new IronMaceItem());
	public static final RegistryObject<Item> DIAMOND_MACE = REGISTRY.register("diamond_mace", () -> new DiamondMaceItem());
	public static final RegistryObject<Item> NETHERITE_MACE = REGISTRY.register("netherite_mace", () -> new NetheriteMaceItem());
	public static final RegistryObject<Item> WOODEN_SCYTHE = REGISTRY.register("wooden_scythe", () -> new WoodenScytheItem());
	public static final RegistryObject<Item> STONE_SCYTHE = REGISTRY.register("stone_scythe", () -> new StoneScytheItem());
	public static final RegistryObject<Item> GOLDEN_SCYTHE = REGISTRY.register("golden_scythe", () -> new GoldenScytheItem());
	public static final RegistryObject<Item> IRON_SCYTHE = REGISTRY.register("iron_scythe", () -> new IronScytheItem());
	public static final RegistryObject<Item> DIAMOND_SCYTHE = REGISTRY.register("diamond_scythe", () -> new DiamondScytheItem());
	public static final RegistryObject<Item> NETHERITE_SCYTHE = REGISTRY.register("netherite_scythe", () -> new NetheriteScytheItem());
	public static final RegistryObject<Item> WOODEN_SABER = REGISTRY.register("wooden_saber", () -> new WoodenSaberItem());
	public static final RegistryObject<Item> STONE_SABER = REGISTRY.register("stone_saber", () -> new StoneSaberItem());
	public static final RegistryObject<Item> GOLDEN_SABER = REGISTRY.register("golden_saber", () -> new GoldenSaberItem());
	public static final RegistryObject<Item> IRON_SABER = REGISTRY.register("iron_saber", () -> new IronSaberItem());
	public static final RegistryObject<Item> DIAMOND_SABER = REGISTRY.register("diamond_saber", () -> new DiamondSaberItem());
	public static final RegistryObject<Item> NETHERITE_SABER = REGISTRY.register("netherite_saber", () -> new NetheriteSaberItem());
	public static final RegistryObject<Item> WOODEN_BATTLE_AXE = REGISTRY.register("wooden_battle_axe", () -> new WoodenBattleAxeItem());
	public static final RegistryObject<Item> STONE_BATTLE_AXE = REGISTRY.register("stone_battle_axe", () -> new StoneBattleAxeItem());
	public static final RegistryObject<Item> GOLDEN_BATTLE_AXE = REGISTRY.register("golden_battle_axe", () -> new GoldenBattleAxeItem());
	public static final RegistryObject<Item> IRON_BATTLE_AXE = REGISTRY.register("iron_battle_axe", () -> new IronBattleAxeItem());
	public static final RegistryObject<Item> DIAMOND_BATTLE_AXE = REGISTRY.register("diamond_battle_axe", () -> new DiamondBattleAxeItem());
	public static final RegistryObject<Item> NETHERITE_BATTLE_AXE = REGISTRY.register("netherite_battle_axe", () -> new NetheriteBattleAxeItem());
	public static final RegistryObject<Item> WOODEN_PIKE = REGISTRY.register("wooden_pike", () -> new WoodenPikeItem());
	public static final RegistryObject<Item> STONE_PIKE = REGISTRY.register("stone_pike", () -> new StonePikeItem());
	public static final RegistryObject<Item> GOLDEN_PIKE = REGISTRY.register("golden_pike", () -> new GoldenPikeItem());
	public static final RegistryObject<Item> IRON_PIKE = REGISTRY.register("iron_pike", () -> new IronPikeItem());
	public static final RegistryObject<Item> DIAMOND_PIKE = REGISTRY.register("diamond_pike", () -> new DiamondPikeItem());
	public static final RegistryObject<Item> NETHERITE_PIKE = REGISTRY.register("netherite_pike", () -> new NetheritePikeItem());
	public static final RegistryObject<Item> WOODEN_LANCE = REGISTRY.register("wooden_lance", () -> new WoodenLanceItem());
	public static final RegistryObject<Item> STONE_LANCE = REGISTRY.register("stone_lance", () -> new StoneLanceItem());
	public static final RegistryObject<Item> GOLDEN_LANCE = REGISTRY.register("golden_lance", () -> new GoldenLanceItem());
	public static final RegistryObject<Item> IRON_LANCE = REGISTRY.register("iron_lance", () -> new IronLanceItem());
	public static final RegistryObject<Item> DIAMOND_LANCE = REGISTRY.register("diamond_lance", () -> new DiamondLanceItem());
	public static final RegistryObject<Item> NETHERITE_LANCE = REGISTRY.register("netherite_lance", () -> new NetheriteLanceItem());
	public static final RegistryObject<Item> WOODEN_MESSER = REGISTRY.register("wooden_messer", () -> new WoodenMesserItem());
	public static final RegistryObject<Item> STONE_MESSER = REGISTRY.register("stone_messer", () -> new StoneMesserItem());
	public static final RegistryObject<Item> GOLDEN_MESSER = REGISTRY.register("golden_messer", () -> new GoldenMesserItem());
	public static final RegistryObject<Item> IRON_MESSER = REGISTRY.register("iron_messer", () -> new IronMesserItem());
	public static final RegistryObject<Item> DIAMOND_MESSER = REGISTRY.register("diamond_messer", () -> new DiamondMesserItem());
	public static final RegistryObject<Item> NETHERITE_MESSER = REGISTRY.register("netherite_messer", () -> new NetheriteMesserItem());
	public static final RegistryObject<Item> WOODEN_KATANA = REGISTRY.register("wooden_katana", () -> new WoodenKatanaItem());
	public static final RegistryObject<Item> STONE_KATANA = REGISTRY.register("stone_katana", () -> new StoneKatanaItem());
	public static final RegistryObject<Item> GOLDEN_KATANA = REGISTRY.register("golden_katana", () -> new GoldenKatanaItem());
	public static final RegistryObject<Item> IRON_KATANA = REGISTRY.register("iron_katana", () -> new IronKatanaItem());
	public static final RegistryObject<Item> DIAMOND_KATANA = REGISTRY.register("diamond_katana", () -> new DiamondKatanaItem());
	public static final RegistryObject<Item> NETHERITE_KATANA = REGISTRY.register("netherite_katana", () -> new NetheriteKatanaItem());
	public static final RegistryObject<Item> WOODEN_GREATSWORD = REGISTRY.register("wooden_greatsword", () -> new WoodenGreatswordItem());
	public static final RegistryObject<Item> STONE_GREATSWORD = REGISTRY.register("stone_greatsword", () -> new StoneGreatswordItem());
	public static final RegistryObject<Item> GOLDEN_GREATSWORD = REGISTRY.register("golden_greatsword", () -> new GoldenGreatswordItem());
	public static final RegistryObject<Item> IRON_GREATSWORD = REGISTRY.register("iron_greatsword", () -> new IronGreatswordItem());
	public static final RegistryObject<Item> DIAMOND_GREATSWORD = REGISTRY.register("diamond_greatsword", () -> new DiamondGreatswordItem());
	public static final RegistryObject<Item> NETHERITE_GREATSWORD = REGISTRY.register("netherite_greatsword", () -> new NetheriteGreatswordItem());
	public static final RegistryObject<Item> WOODEN_GLAIVE = REGISTRY.register("wooden_glaive", () -> new WoodenGlaiveItem());
	public static final RegistryObject<Item> STONE_GLAIVE = REGISTRY.register("stone_glaive", () -> new StoneGlaiveItem());
	public static final RegistryObject<Item> GOLDEN_GLAIVE = REGISTRY.register("golden_glaive", () -> new GoldenGlaiveItem());
	public static final RegistryObject<Item> IRON_GLAIVE = REGISTRY.register("iron_glaive", () -> new IronGlaiveItem());
	public static final RegistryObject<Item> DIAMOND_GLAIVE = REGISTRY.register("diamond_glaive", () -> new DiamondGlaiveItem());
	public static final RegistryObject<Item> NETHERITE_GLAIVE = REGISTRY.register("netherite_glaive", () -> new NetheriteGlaiveItem());
	public static final RegistryObject<Item> WOODEN_EXECUTIONER_SWORD = REGISTRY.register("wooden_executioner_sword", () -> new WoodenExecutionerSwordItem());
	public static final RegistryObject<Item> STONE_EXECUTIONER_SWORD = REGISTRY.register("stone_executioner_sword", () -> new StoneExecutionerSwordItem());
	public static final RegistryObject<Item> GOLDEN_EXECUTIONER_SWORD = REGISTRY.register("golden_executioner_sword", () -> new GoldenExecutionerSwordItem());
	public static final RegistryObject<Item> IRON_EXECUTIONER_SWORD = REGISTRY.register("iron_executioner_sword", () -> new IronExecutionerSwordItem());
	public static final RegistryObject<Item> DIAMOND_EXECUTIONER_SWORD = REGISTRY.register("diamond_executioner_sword", () -> new DiamondExecutionerSwordItem());
	public static final RegistryObject<Item> NETHERITE_EXECUTIONER_SWORD = REGISTRY.register("netherite_executioner_sword", () -> new NetheriteExecutionerSwordItem());
	public static final RegistryObject<Item> WOODEN_TWIN_BLADE = REGISTRY.register("wooden_twin_blade", () -> new WoodenTwinBladeItem());
	public static final RegistryObject<Item> STONE_TWIN_BLADE = REGISTRY.register("stone_twin_blade", () -> new StoneTwinBladeItem());
	public static final RegistryObject<Item> GOLDEN_TWIN_BLADE = REGISTRY.register("golden_twin_blade", () -> new GoldenTwinBladeItem());
	public static final RegistryObject<Item> IRON_TWIN_BLADE = REGISTRY.register("iron_twin_blade", () -> new IronTwinBladeItem());
	public static final RegistryObject<Item> DIAMOND_TWIN_BLADE = REGISTRY.register("diamond_twin_blade", () -> new DiamondTwinBladeItem());
	public static final RegistryObject<Item> NETHERITE_TWIN_BLADE = REGISTRY.register("netherite_twin_blade", () -> new NetheriteTwinBladeItem());
	public static final RegistryObject<Item> RAMROD = REGISTRY.register("ramrod", () -> new RamrodItem());
	public static final RegistryObject<Item> FLINTLOCK_MECHANISM = REGISTRY.register("flintlock_mechanism", () -> new FlintlockMechanismItem());
	public static final RegistryObject<Item> SHORT_BARREL = REGISTRY.register("short_barrel", () -> new ShortBarrelItem());
	public static final RegistryObject<Item> LONG_BARREL = REGISTRY.register("long_barrel", () -> new LongBarrelItem());
	public static final RegistryObject<Item> BLUNDERBUSS_BARREL = REGISTRY.register("blunderbuss_barrel", () -> new BlunderbussBarrelItem());
	public static final RegistryObject<Item> FLINTLOCK_PISTOL = REGISTRY.register("flintlock_pistol", () -> new FlintlockPistolItem());
	public static final RegistryObject<Item> MUSKET = REGISTRY.register("musket", () -> new MusketItem());
	public static final RegistryObject<Item> BLUNDERBUSS = REGISTRY.register("blunderbuss", () -> new BlunderbussItem());
	public static final RegistryObject<Item> MUSKET_BALL = REGISTRY.register("musket_ball", () -> new MusketBallItem());
	public static final RegistryObject<Item> CRACKED_MUSKET_BALL = REGISTRY.register("cracked_musket_ball", () -> new CrackedMusketBallItem());
	public static final RegistryObject<Item> CRYSTALLIZED_MUSKET_BALL = REGISTRY.register("crystallized_musket_ball", () -> new CrystallizedMusketBallItem());
	public static final RegistryObject<Item> FIERY_MUSKET_BALL = REGISTRY.register("fiery_musket_ball", () -> new FieryMusketBallItem());
	public static final RegistryObject<Item> HELLFIRE_MUSKET_BALL = REGISTRY.register("hellfire_musket_ball", () -> new HellfireMusketBallItem());
	public static final RegistryObject<Item> SPIKED_MUSKET_BALL = REGISTRY.register("spiked_musket_ball", () -> new SpikedMusketBallItem());
	public static final RegistryObject<Item> ENDER_BALL = REGISTRY.register("ender_ball", () -> new EnderBallItem());
	public static final RegistryObject<Item> MUSKET_BALL_PIECE = REGISTRY.register("musket_ball_piece", () -> new MusketBallPieceItem());
	public static final RegistryObject<Item> CRYSTAL_PIECE = REGISTRY.register("crystal_piece", () -> new CrystalPieceItem());
	public static final RegistryObject<Item> EXPLOSIVE_MUSKET_BALL = REGISTRY.register("explosive_musket_ball", () -> new ExplosiveMusketBallItem());
	public static final RegistryObject<Item> HEAVY_MUSKET_BALL = REGISTRY.register("heavy_musket_ball", () -> new HeavyMusketBallItem());
	public static final RegistryObject<Item> DPS_METER = REGISTRY.register("dps_meter", () -> new DPSMeterItem());
	public static final RegistryObject<Item> SOUL_EATER = REGISTRY.register("soul_eater", () -> new SoulEaterItem());
	public static final RegistryObject<Item> FROSTMAW = REGISTRY.register("frostmaw", () -> new FrostmawItem());
	public static final RegistryObject<Item> ECHOING_SICKLE = REGISTRY.register("echoing_sickle", () -> new EchoingSickleItem());
	public static final RegistryObject<Item> NATURES_JUDGEMENT = REGISTRY.register("natures_judgement", () -> new NaturesJudgementItem());
	public static final RegistryObject<Item> TRAITORS_DAGGER = REGISTRY.register("traitors_dagger", () -> new TraitorsGreedItem());
	public static final RegistryObject<Item> BLAZE_ROD_HANDLE = REGISTRY.register("blaze_rod_handle", () -> new BlazeRodHandleItem());
	public static final RegistryObject<Item> THOUSAND_CUTS = REGISTRY.register("thousand_cuts", () -> new ThousandCutsItem());
	public static final RegistryObject<Item> RETRIBUTION = REGISTRY.register("retribution", () -> new RetributionItem());
	public static final RegistryObject<Item> DEATH_SCYTHE = REGISTRY.register("death_scythe", () -> new DeathScytheItem());
	public static final RegistryObject<Item> WOODEN_SPEAR = REGISTRY.register("wooden_spear", () -> new WoodenSpearItem());
	public static final RegistryObject<Item> STONE_SPEAR = REGISTRY.register("stone_spear", () -> new StoneSpearItem());
	public static final RegistryObject<Item> GOLDEN_SPEAR = REGISTRY.register("golden_spear", () -> new GoldenSpearItem());
	public static final RegistryObject<Item> IRON_SPEAR = REGISTRY.register("iron_spear", () -> new IronSpearItem());
	public static final RegistryObject<Item> DIAMOND_SPEAR = REGISTRY.register("diamond_spear", () -> new DiamondSpearItem());
	public static final RegistryObject<Item> NETHERITE_SPEAR = REGISTRY.register("netherite_spear", () -> new NetheriteSpearItem());
	public static final RegistryObject<Item> CATASTROPHE = REGISTRY.register("catastrophe", () -> new CatastropheItem());
	public static final RegistryObject<Item> BLAZE_ROD_POLE = REGISTRY.register("blaze_rod_pole", () -> new BlazeRodPoleItem());
	public static final RegistryObject<Item> KRAKEN_HUNTER = REGISTRY.register("kraken_hunter", () -> new KrakenHunterItem());
	public static final RegistryObject<Item> HEADSMAN = REGISTRY.register("headsman", () -> new HeadsmanItem());
	public static final RegistryObject<Item> DIAMOND_SHIELD = REGISTRY.register("diamond_shield", () -> new DiamondShieldItem());
	public static final RegistryObject<Item> NETHERITE_SHIELD = REGISTRY.register("netherite_shield", () -> new NetheriteShieldItem());
	public static final RegistryObject<Item> EXPLOSIVE_SHIELD = REGISTRY.register("explosive_shield", () -> new ExplosiveShieldItem());
	public static final RegistryObject<Item> BUCKLER = REGISTRY.register("buckler", () -> new BucklerItem());
	public static final RegistryObject<Item> SPIKED_SHIELD = REGISTRY.register("spiked_shield", () -> new SpikedShieldItem());
	public static final RegistryObject<Item> ENDER_SHIELD = REGISTRY.register("ender_shield", () -> new EnderShieldItem());
	public static final RegistryObject<Item> LIVING_SHIELD = REGISTRY.register("living_shield", () -> new LivingShieldItem());
	public static final RegistryObject<Item> ASSAULT_SHIELD = REGISTRY.register("assault_shield", () -> new AssaultShieldItem());
	public static final RegistryObject<Item> OPPOSING_WINDS = REGISTRY.register("opposing_winds", () -> new OpposingWindsItem());
	public static final RegistryObject<Item> ESTOC = REGISTRY.register("estoc", () -> new EstocItem());
	public static final RegistryObject<Item> WOODEN_FLAIL = REGISTRY.register("wooden_flail", () -> new WoodenFlailItem());
	public static final RegistryObject<Item> STONE_FLAIL = REGISTRY.register("stone_flail", () -> new StoneFlailItem());
	public static final RegistryObject<Item> GOLDEN_FLAIL = REGISTRY.register("golden_flail", () -> new GoldenFlailItem());
	public static final RegistryObject<Item> IRON_FLAIL = REGISTRY.register("iron_flail", () -> new IronFlailItem());
	public static final RegistryObject<Item> DIAMOND_FLAIL = REGISTRY.register("diamond_flail", () -> new DiamondFlailItem());
	public static final RegistryObject<Item> NETHERITE_FLAIL = REGISTRY.register("netherite_flail", () -> new NetheriteFlailItem());
	public static final RegistryObject<Item> WOODEN_PARRYING_DAGGER = REGISTRY.register("wooden_parrying_dagger", () -> new WoodenParryingDaggerItem());
	public static final RegistryObject<Item> STONE_PARRYING_DAGGER = REGISTRY.register("stone_parrying_dagger", () -> new StoneParryingDaggerItem());
	public static final RegistryObject<Item> IRON_PARRYING_DAGGER = REGISTRY.register("iron_parrying_dagger", () -> new IronParryingDaggerItem());
	public static final RegistryObject<Item> GOLDEN_PARRYING_DAGGER = REGISTRY.register("golden_parrying_dagger", () -> new GoldenParryingDaggerItem());
	public static final RegistryObject<Item> DIAMOND_PARRYING_DAGGER = REGISTRY.register("diamond_parrying_dagger", () -> new DiamondParryingDaggerItem());
	public static final RegistryObject<Item> NETHERITE_PARRYING_DAGGER = REGISTRY.register("netherite_parrying_dagger", () -> new NetheriteParryingDaggerItem());
	public static final RegistryObject<Item> WOODEN_LONGSWORD = REGISTRY.register("wooden_longsword", () -> new WoodenLongswordItem());
	public static final RegistryObject<Item> STONE_LONGSWORD = REGISTRY.register("stone_longsword", () -> new StoneLongswordItem());
	public static final RegistryObject<Item> GOLDEN_LONGSWORD = REGISTRY.register("golden_longsword", () -> new GoldenLongswordItem());
	public static final RegistryObject<Item> IRON_LONGSWORD = REGISTRY.register("iron_longsword", () -> new IronLongswordItem());
	public static final RegistryObject<Item> DIAMOND_LONGSWORD = REGISTRY.register("diamond_longsword", () -> new DiamondLongswordItem());
	public static final RegistryObject<Item> NETHERITE_LONGSWORD = REGISTRY.register("netherite_longsword", () -> new NetheriteLongswordItem());
	public static final RegistryObject<Item> STEEL_GLADIUS = REGISTRY.register("steel_gladius", () -> new SteelGladiusItem());
	public static final RegistryObject<Item> STEEL_DAGGER = REGISTRY.register("steel_dagger", () -> new SteelDaggerItem());
	public static final RegistryObject<Item> STEEL_RAPIER = REGISTRY.register("steel_rapier", () -> new SteelRapierItem());
	public static final RegistryObject<Item> STEEL_KHOPESH = REGISTRY.register("steel_khopesh", () -> new SteelKhopeshItem());
	public static final RegistryObject<Item> STEEL_WARHAMMER = REGISTRY.register("steel_warhammer", () -> new SteelWarhammerItem());
	public static final RegistryObject<Item> STEEL_SICKLE = REGISTRY.register("steel_sickle", () -> new SteelSickleItem());
	public static final RegistryObject<Item> STEEL_MACE = REGISTRY.register("steel_mace", () -> new SteelMaceItem());
	public static final RegistryObject<Item> STEEL_SABER = REGISTRY.register("steel_saber", () -> new SteelSaberItem());
	public static final RegistryObject<Item> STEEL_BATTLE_AXE = REGISTRY.register("steel_battle_axe", () -> new SteelBattleAxeItem());
	public static final RegistryObject<Item> STEEL_MESSER = REGISTRY.register("steel_messer", () -> new SteelMesserItem());
	public static final RegistryObject<Item> STEEL_KATANA = REGISTRY.register("steel_katana", () -> new SteelKatanaItem());
	public static final RegistryObject<Item> STEEL_FLAIL = REGISTRY.register("steel_flail", () -> new SteelFlailItem());
	public static final RegistryObject<Item> STEEL_PARRYING_DAGGER = REGISTRY.register("steel_parrying_dagger", () -> new SteelParryingDaggerItem());
	public static final RegistryObject<Item> STEEL_SPEAR = REGISTRY.register("steel_spear", () -> new SteelSpearItem());
	public static final RegistryObject<Item> STEEL_HALBERD = REGISTRY.register("steel_halberd", () -> new SteelHalberdItem());
	public static final RegistryObject<Item> STEEL_SCYTHE = REGISTRY.register("steel_scythe", () -> new SteelScytheItem());
	public static final RegistryObject<Item> STEEL_PIKE = REGISTRY.register("steel_pike", () -> new SteelPikeItem());
	public static final RegistryObject<Item> STEEL_LANCE = REGISTRY.register("steel_lance", () -> new SteelLanceItem());
	public static final RegistryObject<Item> STEEL_GREATSWORD = REGISTRY.register("steel_greatsword", () -> new SteelGreatswordItem());
	public static final RegistryObject<Item> STEEL_GLAIVE = REGISTRY.register("steel_glaive", () -> new SteelGlaiveItem());
	public static final RegistryObject<Item> STEEL_EXECUTIONER_SWORD = REGISTRY.register("steel_executioner_sword", () -> new SteelExecutionerSwordItem());
	public static final RegistryObject<Item> STEEL_TWIN_BLADE = REGISTRY.register("steel_twin_blade", () -> new SteelTwinBladeItem());
	public static final RegistryObject<Item> STEEL_LONGSWORD = REGISTRY.register("steel_longsword", () -> new SteelLongswordItem());
	public static final RegistryObject<Item> BRONZE_GLADIUS = REGISTRY.register("bronze_gladius", () -> new BronzeGladiusItem());
	public static final RegistryObject<Item> BRONZE_DAGGER = REGISTRY.register("bronze_dagger", () -> new BronzeDaggerItem());
	public static final RegistryObject<Item> BRONZE_RAPIER = REGISTRY.register("bronze_rapier", () -> new BronzeRapierItem());
	public static final RegistryObject<Item> BRONZE_KHOPESH = REGISTRY.register("bronze_khopesh", () -> new BronzeKhopeshItem());
	public static final RegistryObject<Item> BRONZE_WARHAMMER = REGISTRY.register("bronze_warhammer", () -> new BronzeWarhammerItem());
	public static final RegistryObject<Item> BRONZE_SICKLE = REGISTRY.register("bronze_sickle", () -> new BronzeSickleItem());
	public static final RegistryObject<Item> BRONZE_MACE = REGISTRY.register("bronze_mace", () -> new BronzeMaceItem());
	public static final RegistryObject<Item> BRONZE_SABER = REGISTRY.register("bronze_saber", () -> new BronzeSaberItem());
	public static final RegistryObject<Item> BRONZE_BATTLE_AXE = REGISTRY.register("bronze_battle_axe", () -> new BronzeBattleAxeItem());
	public static final RegistryObject<Item> BRONZE_MESSER = REGISTRY.register("bronze_messer", () -> new BronzeMesserItem());
	public static final RegistryObject<Item> BRONZE_KATANA = REGISTRY.register("bronze_katana", () -> new BronzeKatanaItem());
	public static final RegistryObject<Item> BRONZE_FLAIL = REGISTRY.register("bronze_flail", () -> new BronzeFlailItem());
	public static final RegistryObject<Item> BRONZE_PARRYING_DAGGER = REGISTRY.register("bronze_parrying_dagger", () -> new BronzeParryingDaggerItem());
	public static final RegistryObject<Item> BRONZE_SPEAR = REGISTRY.register("bronze_spear", () -> new BronzeSpearItem());
	public static final RegistryObject<Item> BRONZE_HALBERD = REGISTRY.register("bronze_halberd", () -> new BronzeHalberdItem());
	public static final RegistryObject<Item> BRONZE_SCYTHE = REGISTRY.register("bronze_scythe", () -> new BronzeScytheItem());
	public static final RegistryObject<Item> BRONZE_PIKE = REGISTRY.register("bronze_pike", () -> new BronzePikeItem());
	public static final RegistryObject<Item> BRONZE_LANCE = REGISTRY.register("bronze_lance", () -> new BronzeLanceItem());
	public static final RegistryObject<Item> BRONZE_GREATSWORD = REGISTRY.register("bronze_greatsword", () -> new BronzeGreatswordItem());
	public static final RegistryObject<Item> BRONZE_GLAIVE = REGISTRY.register("bronze_glaive", () -> new BronzeGlaiveItem());
	public static final RegistryObject<Item> BRONZE_EXECUTIONER_SWORD = REGISTRY.register("bronze_executioner_sword", () -> new BronzeExecutionerSwordItem());
	public static final RegistryObject<Item> BRONZE_TWIN_BLADE = REGISTRY.register("bronze_twin_blade", () -> new BronzeTwinBladeItem());
	public static final RegistryObject<Item> BRONZE_LONGSWORD = REGISTRY.register("bronze_longsword", () -> new BronzeLongswordItem());
	public static final RegistryObject<Item> SILVER_GLADIUS = REGISTRY.register("silver_gladius", () -> new SilverGladiusItem());
	public static final RegistryObject<Item> SILVER_DAGGER = REGISTRY.register("silver_dagger", () -> new SilverDaggerItem());
	public static final RegistryObject<Item> SILVER_RAPIER = REGISTRY.register("silver_rapier", () -> new SilverRapierItem());
	public static final RegistryObject<Item> SILVER_KHOPESH = REGISTRY.register("silver_khopesh", () -> new SilverKhopeshItem());
	public static final RegistryObject<Item> SILVER_WARHAMMER = REGISTRY.register("silver_warhammer", () -> new SilverWarhammerItem());
	public static final RegistryObject<Item> SILVER_SICKLE = REGISTRY.register("silver_sickle", () -> new SilverSickleItem());
	public static final RegistryObject<Item> SILVER_MACE = REGISTRY.register("silver_mace", () -> new SilverMaceItem());
	public static final RegistryObject<Item> SILVER_SABER = REGISTRY.register("silver_saber", () -> new SilverSaberItem());
	public static final RegistryObject<Item> SILVER_BATTLE_AXE = REGISTRY.register("silver_battle_axe", () -> new SilverBattleAxeItem());
	public static final RegistryObject<Item> SILVER_MESSER = REGISTRY.register("silver_messer", () -> new SilverMesserItem());
	public static final RegistryObject<Item> SILVER_KATANA = REGISTRY.register("silver_katana", () -> new SilverKatanaItem());
	public static final RegistryObject<Item> SILVER_FLAIL = REGISTRY.register("silver_flail", () -> new SilverFlailItem());
	public static final RegistryObject<Item> SILVER_PARRYING_DAGGER = REGISTRY.register("silver_parrying_dagger", () -> new SilverParryingDaggerItem());
	public static final RegistryObject<Item> SILVER_SPEAR = REGISTRY.register("silver_spear", () -> new SilverSpearItem());
	public static final RegistryObject<Item> SILVER_HALBERD = REGISTRY.register("silver_halberd", () -> new SilverHalberdItem());
	public static final RegistryObject<Item> SILVER_SCYTHE = REGISTRY.register("silver_scythe", () -> new SilverScytheItem());
	public static final RegistryObject<Item> SILVER_PIKE = REGISTRY.register("silver_pike", () -> new SilverPikeItem());
	public static final RegistryObject<Item> SILVER_LANCE = REGISTRY.register("silver_lance", () -> new SilverLanceItem());
	public static final RegistryObject<Item> SILVER_GREATSWORD = REGISTRY.register("silver_greatsword", () -> new SilverGreatswordItem());
	public static final RegistryObject<Item> SILVER_GLAIVE = REGISTRY.register("silver_glaive", () -> new SilverGlaiveItem());
	public static final RegistryObject<Item> SILVER_EXECUTIONER_SWORD = REGISTRY.register("silver_executioner_sword", () -> new SilverExecutionerSwordItem());
	public static final RegistryObject<Item> SILVER_TWIN_BLADE = REGISTRY.register("silver_twin_blade", () -> new SilverTwinBladeItem());
	public static final RegistryObject<Item> SILVER_LONGSWORD = REGISTRY.register("silver_longsword", () -> new SilverLongswordItem());
	public static final RegistryObject<Item> ROSE_GOLD_GLADIUS = REGISTRY.register("rose_gold_gladius", () -> new RoseGoldGladiusItem());
	public static final RegistryObject<Item> ROSE_GOLD_DAGGER = REGISTRY.register("rose_gold_dagger", () -> new RoseGoldDaggerItem());
	public static final RegistryObject<Item> ROSE_GOLD_RAPIER = REGISTRY.register("rose_gold_rapier", () -> new RoseGoldRapierItem());
	public static final RegistryObject<Item> ROSE_GOLD_KHOPESH = REGISTRY.register("rose_gold_khopesh", () -> new RoseGoldKhopeshItem());
	public static final RegistryObject<Item> ROSE_GOLD_WARHAMMER = REGISTRY.register("rose_gold_warhammer", () -> new RoseGoldWarhammerItem());
	public static final RegistryObject<Item> ROSE_GOLD_SICKLE = REGISTRY.register("rose_gold_sickle", () -> new RoseGoldSickleItem());
	public static final RegistryObject<Item> ROSE_GOLD_MACE = REGISTRY.register("rose_gold_mace", () -> new RoseGoldMaceItem());
	public static final RegistryObject<Item> ROSE_GOLD_SABER = REGISTRY.register("rose_gold_saber", () -> new RoseGoldSaberItem());
	public static final RegistryObject<Item> ROSE_GOLD_BATTLE_AXE = REGISTRY.register("rose_gold_battle_axe", () -> new RoseGoldBattleAxeItem());
	public static final RegistryObject<Item> ROSE_GOLD_MESSER = REGISTRY.register("rose_gold_messer", () -> new RoseGoldMesserItem());
	public static final RegistryObject<Item> ROSE_GOLD_KATANA = REGISTRY.register("rose_gold_katana", () -> new RoseGoldKatanaItem());
	public static final RegistryObject<Item> ROSE_GOLD_FLAIL = REGISTRY.register("rose_gold_flail", () -> new RoseGoldFlailItem());
	public static final RegistryObject<Item> ROSE_GOLD_PARRYING_DAGGER = REGISTRY.register("rose_gold_parrying_dagger", () -> new RoseGoldParryingDaggerItem());
	public static final RegistryObject<Item> ROSE_GOLD_SPEAR = REGISTRY.register("rose_gold_spear", () -> new RoseGoldSpearItem());
	public static final RegistryObject<Item> ROSE_GOLD_HALBERD = REGISTRY.register("rose_gold_halberd", () -> new RoseGoldHalberdItem());
	public static final RegistryObject<Item> ROSE_GOLD_SCYTHE = REGISTRY.register("rose_gold_scythe", () -> new RoseGoldScytheItem());
	public static final RegistryObject<Item> ROSE_GOLD_PIKE = REGISTRY.register("rose_gold_pike", () -> new RoseGoldPikeItem());
	public static final RegistryObject<Item> ROSE_GOLD_LANCE = REGISTRY.register("rose_gold_lance", () -> new RoseGoldLanceItem());
	public static final RegistryObject<Item> ROSE_GOLD_GREATSWORD = REGISTRY.register("rose_gold_greatsword", () -> new RoseGoldGreatswordItem());
	public static final RegistryObject<Item> ROSE_GOLD_GLAIVE = REGISTRY.register("rose_gold_glaive", () -> new RoseGoldGlaiveItem());
	public static final RegistryObject<Item> ROSE_GOLD_EXECUTIONER_SWORD = REGISTRY.register("rose_gold_executioner_sword", () -> new RoseGoldExecutionerSwordItem());
	public static final RegistryObject<Item> ROSE_GOLD_TWIN_BLADE = REGISTRY.register("rose_gold_twin_blade", () -> new RoseGoldTwinBladeItem());
	public static final RegistryObject<Item> ROSE_GOLD_LONGSWORD = REGISTRY.register("rose_gold_longsword", () -> new RoseGoldLongswordItem());
	public static final RegistryObject<Item> GLASS_FLASK = REGISTRY.register("glass_flask", () -> new GlassFlaskItem());
	public static final RegistryObject<Item> WATER_FLASK = REGISTRY.register("water_flask", () -> new WaterFlaskItem());
	public static final RegistryObject<Item> AWKWARD_FLASK = REGISTRY.register("awkward_flask", () -> new AwkwardFlaskItem());
	public static final RegistryObject<Item> MUNDANE_FLASK = REGISTRY.register("mundane_flask", () -> new MundaneFlaskItem());
	public static final RegistryObject<Item> THICK_FLASK = REGISTRY.register("thick_flask", () -> new ThickFlaskItem());
	public static final RegistryObject<Item> FLASK_OF_POISON = REGISTRY.register("flask_of_poison", () -> new FlaskOfPoisonItem());
	public static final RegistryObject<Item> FLASK_OF_BLINDNESS = REGISTRY.register("flask_of_blindness", () -> new FlaskOfBlindnessItem());
	public static final RegistryObject<Item> FLASK_OF_FIRE = REGISTRY.register("flask_of_fire", () -> new FlaskOfFireItem());
	public static final RegistryObject<Item> FLASK_OF_SOUL_FIRE = REGISTRY.register("flask_of_soul_fire", () -> new FlaskOfSoulFireItem());
	public static final RegistryObject<Item> FLASK_OF_SLOWNESS = REGISTRY.register("flask_of_slowness", () -> new FlaskOfSlownessItem());
	public static final RegistryObject<Item> FLASK_OF_WITHER = REGISTRY.register("flask_of_wither", () -> new FlaskOfWitherItem());
	public static final RegistryObject<Item> FLASK_OF_SLOW_FALLING = REGISTRY.register("flask_of_slow_falling", () -> new FlaskOfSlowFallingItem());
	public static final RegistryObject<Item> FLASK_OF_GLOWING = REGISTRY.register("flask_of_glowing", () -> new FlaskOfGlowingItem());
	public static final RegistryObject<Item> FLASK_OF_LIGHTNING = REGISTRY.register("flask_of_lightning", () -> new FlaskOfLightningItem());
	public static final RegistryObject<Item> FLASK_OF_GUNPOWDER = REGISTRY.register("flask_of_gunpowder", () -> new FlaskOfGunpowderItem());
	public static final RegistryObject<Item> FLASK_OF_VOLATILE_CONCOCTION = REGISTRY.register("flask_of_volatile_concoction", () -> new FlaskOfVolatileConcoctionItem());
	public static final RegistryObject<Item> FLASK_OF_LEVITATION = REGISTRY.register("flask_of_levitation", () -> new FlaskOfLevitationItem());
	public static final RegistryObject<Item> FLASK_OF_WEAKNESS = REGISTRY.register("flask_of_weakness", () -> new FlaskOfWeaknessItem());
	public static final RegistryObject<Item> WOODEN_SCHIAVONA = REGISTRY.register("wooden_schiavona", () -> new WoodenSchiavonaItem());
	public static final RegistryObject<Item> STONE_SCHIAVONA = REGISTRY.register("stone_schiavona", () -> new StoneSchiavonaItem());
	public static final RegistryObject<Item> GOLDEN_SCHIAVONA = REGISTRY.register("golden_schiavona", () -> new GoldenSchiavonaItem());
	public static final RegistryObject<Item> IRON_SCHIAVONA = REGISTRY.register("iron_schiavona", () -> new IronSchiavonaItem());
	public static final RegistryObject<Item> DIAMOND_SCHIAVONA = REGISTRY.register("diamond_schiavona", () -> new DiamondSchiavonaItem());
	public static final RegistryObject<Item> NETHERITE_SCHIAVONA = REGISTRY.register("netherite_schiavona", () -> new NetheriteSchiavonaItem());
	public static final RegistryObject<Item> STEEL_SCHIAVONA = REGISTRY.register("steel_schiavona", () -> new SteelSchiavonaItem());
	public static final RegistryObject<Item> SILVER_SCHIAVONA = REGISTRY.register("silver_schiavona", () -> new SilverSchiavonaItem());
	public static final RegistryObject<Item> BRONZE_SCHIAVONA = REGISTRY.register("bronze_schiavona", () -> new BronzeSchiavonaItem());
	public static final RegistryObject<Item> ROSE_GOLD_SCHIAVONA = REGISTRY.register("rose_gold_schiavona", () -> new RoseGoldSchiavonaItem());
	public static final RegistryObject<Item> IRON_BOW = REGISTRY.register("iron_bow", () -> new IronBowItem());
	public static final RegistryObject<Item> DIAMOND_BOW = REGISTRY.register("diamond_bow", () -> new DiamondBowItem());
	public static final RegistryObject<Item> NETHERITE_BOW = REGISTRY.register("netherite_bow", () -> new NetheriteBowItem());
	public static final RegistryObject<Item> AUTO_BOW = REGISTRY.register("auto_bow", () -> new AutoBowItem());
	public static final RegistryObject<Item> SUN_FURY = REGISTRY.register("sun_fury", () -> new SunFuryItem());
	public static final RegistryObject<Item> DIAMOND_BUCKLER = REGISTRY.register("diamond_buckler", () -> new DiamondBucklerItem());
	public static final RegistryObject<Item> SERAPH = REGISTRY.register("seraph", () -> new SeraphItem());
	public static final RegistryObject<Item> QUIVER = REGISTRY.register("quiver", () -> new QuiverItem());
	public static final RegistryObject<Item> ORNATE_QUIVER = REGISTRY.register("ornate_quiver", () -> new OrnateQuiverItem());
	public static final RegistryObject<Item> NETHERITE_QUIVER = REGISTRY.register("netherite_quiver", () -> new NetheriteQuiverItem());
	public static final RegistryObject<Item> MUSKET_BALL_POUCH = REGISTRY.register("musket_ball_pouch", () -> new MusketBallPouchItem());
	public static final RegistryObject<Item> WOODEN_FALCHION = REGISTRY.register("wooden_falchion", () -> new WoodenFalchionItem());
	public static final RegistryObject<Item> STONE_FALCHION = REGISTRY.register("stone_falchion", () -> new StoneFalchionItem());
	public static final RegistryObject<Item> GOLDEN_FALCHION = REGISTRY.register("golden_falchion", () -> new GoldenFalchionItem());
	public static final RegistryObject<Item> IRON_FALCHION = REGISTRY.register("iron_falchion", () -> new IronFalchionItem());
	public static final RegistryObject<Item> DIAMOND_FALCHION = REGISTRY.register("diamond_falchion", () -> new DiamondFalchionItem());
	public static final RegistryObject<Item> NETHERITE_FALCHION = REGISTRY.register("netherite_falchion", () -> new NetheriteFalchionItem());
	public static final RegistryObject<Item> STEEL_FALCHION = REGISTRY.register("steel_falchion", () -> new SteelFalchionItem());
	public static final RegistryObject<Item> BRONZE_FALCHION = REGISTRY.register("bronze_falchion", () -> new BronzeFalchionItem());
	public static final RegistryObject<Item> SILVER_FALCHION = REGISTRY.register("silver_falchion", () -> new SilverFalchionItem());
	public static final RegistryObject<Item> ROSE_GOLD_FALCHION = REGISTRY.register("rose_gold_falchion", () -> new RoseGoldFalchionItem());
	public static final RegistryObject<Item> SEALED_SHIELD = REGISTRY.register("sealed_shield", () -> new SealedShieldItem());
	public static final RegistryObject<Item> PHANTOM_MUSKET_BALL = REGISTRY.register("phantom_musket_ball", () -> new PhantomMusketBallItem());
	public static final RegistryObject<Item> WOODEN_CHAKRAM = REGISTRY.register("wooden_chakram", () -> new WoodenChakramItem());
	public static final RegistryObject<Item> STONE_CHAKRAM = REGISTRY.register("stone_chakram", () -> new StoneChakramItem());
	public static final RegistryObject<Item> IRON_CHAKRAM = REGISTRY.register("iron_chakram", () -> new IronChakramItem());
	public static final RegistryObject<Item> GOLDEN_CHAKRAM = REGISTRY.register("golden_chakram", () -> new GoldenChakramItem());
	public static final RegistryObject<Item> DIAMOND_CHAKRAM = REGISTRY.register("diamond_chakram", () -> new DiamondChakramItem());
	public static final RegistryObject<Item> NETHERITE_CHAKRAM = REGISTRY.register("netherite_chakram", () -> new NetheriteChakramItem());
	public static final RegistryObject<Item> WOODEN_THROWING_KNIFE = REGISTRY.register("wooden_throwing_knife", () -> new WoodenThrowingKnifeItem());
	public static final RegistryObject<Item> STONE_THROWING_KNIFE = REGISTRY.register("stone_throwing_knife", () -> new StoneThrowingKnifeItem());
	public static final RegistryObject<Item> IRON_THROWING_KNIFE = REGISTRY.register("iron_throwing_knife", () -> new IronThrowingKnifeItem());
	public static final RegistryObject<Item> GOLDEN_THROWING_KNIFE = REGISTRY.register("golden_throwing_knife", () -> new GoldenThrowingKnifeItem());
	public static final RegistryObject<Item> DIAMOND_THROWING_KNIFE = REGISTRY.register("diamond_throwing_knife", () -> new DiamondThrowingKnifeItem());
	public static final RegistryObject<Item> NETHERITE_THROWING_KNIFE = REGISTRY.register("netherite_throwing_knife", () -> new NetheriteThrowingKnifeItem());
	public static final RegistryObject<Item> OBSIDIAN_KNIFE = REGISTRY.register("obsidian_knife", () -> new ObsidianKnifeItem());
	public static final RegistryObject<Item> WOODEN_JAVELIN = REGISTRY.register("wooden_javelin", () -> new WoodenJavelinItem());
	public static final RegistryObject<Item> STONE_JAVELIN = REGISTRY.register("stone_javelin", () -> new StoneJavelinItem());
	public static final RegistryObject<Item> GOLDEN_JAVELIN = REGISTRY.register("golden_javelin", () -> new GoldenJavelinItem());
	public static final RegistryObject<Item> IRON_JAVELIN = REGISTRY.register("iron_javelin", () -> new IronJavelinItem());
	public static final RegistryObject<Item> DIAMOND_JAVELIN = REGISTRY.register("diamond_javelin", () -> new DiamondJavelinItem());
	public static final RegistryObject<Item> NETHERITE_JAVELIN = REGISTRY.register("netherite_javelin", () -> new NetheriteJavelinItem());
	public static final RegistryObject<Item> STEEL_JAVELIN = REGISTRY.register("steel_javelin", () -> new SteelJavelinItem());
	public static final RegistryObject<Item> BRONZE_JAVELIN = REGISTRY.register("bronze_javelin", () -> new BronzeJavelinItem());
	public static final RegistryObject<Item> SILVER_JAVELIN = REGISTRY.register("silver_javelin", () -> new SilverJavelinItem());
	public static final RegistryObject<Item> ROSE_GOLD_JAVELIN = REGISTRY.register("rose_gold_javelin", () -> new RoseGoldJavelinItem());
	public static final RegistryObject<Item> WOODEN_QUARTERSTAFF = REGISTRY.register("wooden_quarterstaff", () -> new WoodenQuarterstaffItem());
	public static final RegistryObject<Item> STONE_QUARTERSTAFF = REGISTRY.register("stone_quarterstaff", () -> new StoneQuarterstaffItem());
	public static final RegistryObject<Item> GOLDEN_QUARTERSTAFF = REGISTRY.register("golden_quarterstaff", () -> new GoldenQuarterstaffItem());
	public static final RegistryObject<Item> IRON_QUARTERSTAFF = REGISTRY.register("iron_quarterstaff", () -> new IronQuarterstaffItem());
	public static final RegistryObject<Item> DIAMOND_QUARTERSTAFF = REGISTRY.register("diamond_quarterstaff", () -> new DiamondQuarterstaffItem());
	public static final RegistryObject<Item> NETHERITE_QUARTERSTAFF = REGISTRY.register("netherite_quarterstaff", () -> new NetheriteQuarterstaffItem());
	public static final RegistryObject<Item> STEEL_QUARTERSTAFF = REGISTRY.register("steel_quarterstaff", () -> new SteelQuarterstaffItem());
	public static final RegistryObject<Item> BRONZE_QUARTERSTAFF = REGISTRY.register("bronze_quarterstaff", () -> new BronzeQuarterstaffItem());
	public static final RegistryObject<Item> SILVER_QUARTERSTAFF = REGISTRY.register("silver_quarterstaff", () -> new SilverQuarterstaffItem());
	public static final RegistryObject<Item> ROSE_GOLD_QUARTERSTAFF = REGISTRY.register("rose_gold_quarterstaff", () -> new RoseGoldQuarterstaffItem());
	public static final RegistryObject<Item> NECROSTAFF = REGISTRY.register("necrostaff", () -> new NecrostaffItem());
	public static final RegistryObject<Item> WOODEN_ODACHI = REGISTRY.register("wooden_odachi", () -> new WoodenOdachiItem());
	public static final RegistryObject<Item> STONE_ODACHI = REGISTRY.register("stone_odachi", () -> new StoneOdachiItem());
	public static final RegistryObject<Item> GOLDEN_ODACHI = REGISTRY.register("golden_odachi", () -> new GoldenOdachiItem());
	public static final RegistryObject<Item> IRON_ODACHI = REGISTRY.register("iron_odachi", () -> new IronOdachiItem());
	public static final RegistryObject<Item> DIAMOND_ODACHI = REGISTRY.register("diamond_odachi", () -> new DiamondOdachiItem());
	public static final RegistryObject<Item> NETHERITE_ODACHI = REGISTRY.register("netherite_odachi", () -> new NetheriteOdachiItem());
	public static final RegistryObject<Item> STEEL_ODACHI = REGISTRY.register("steel_odachi", () -> new SteelOdachiItem());
	public static final RegistryObject<Item> BRONZE_ODACHI = REGISTRY.register("bronze_odachi", () -> new BronzeOdachiItem());
	public static final RegistryObject<Item> SILVER_ODACHI = REGISTRY.register("silver_odachi", () -> new SilverOdachiItem());
	public static final RegistryObject<Item> ROSE_GOLD_ODACHI = REGISTRY.register("rose_gold_odachi", () -> new RoseGoldOdachiItem());
	public static final RegistryObject<Item> COPPER_SABER = REGISTRY.register("copper_saber", () -> new CopperSaberItem());
	public static final RegistryObject<Item> COPPER_BATTLE_AXE = REGISTRY.register("copper_battle_axe", () -> new CopperBattleAxeItem());
	public static final RegistryObject<Item> COPPER_FLAIL = REGISTRY.register("copper_flail", () -> new CopperFlailItem());
	public static final RegistryObject<Item> COPPER_GLADIUS = REGISTRY.register("copper_gladius", () -> new CopperGladiusItem());
	public static final RegistryObject<Item> COPPER_DAGGER = REGISTRY.register("copper_dagger", () -> new CopperDaggerItem());
	public static final RegistryObject<Item> COPPER_RAPIER = REGISTRY.register("copper_rapier", () -> new CopperRapierItem());
	public static final RegistryObject<Item> COPPER_KHOPESH = REGISTRY.register("copper_khopesh", () -> new CopperKhopeshItem());
	public static final RegistryObject<Item> COPPER_WARHAMMER = REGISTRY.register("copper_warhammer", () -> new CopperWarhammerItem());
	public static final RegistryObject<Item> COPPER_SICKLE = REGISTRY.register("copper_sickle", () -> new CopperSickleItem());
	public static final RegistryObject<Item> COPPER_MESSER = REGISTRY.register("copper_messer", () -> new CopperMesserItem());
	public static final RegistryObject<Item> COPPER_PARRYING_DAGGER = REGISTRY.register("copper_parrying_dagger", () -> new CopperParryingDaggerItem());
	public static final RegistryObject<Item> COPPER_MACE = REGISTRY.register("copper_mace", () -> new CopperMaceItem());
	public static final RegistryObject<Item> COPPER_KATANA = REGISTRY.register("copper_katana", () -> new CopperKatanaItem());
	public static final RegistryObject<Item> COPPER_SCHIAVONA = REGISTRY.register("copper_schiavona", () -> new CopperSchiavonaItem());
	public static final RegistryObject<Item> COPPER_FALCHION = REGISTRY.register("copper_falchion", () -> new CopperFalchionItem());
	public static final RegistryObject<Item> COPPER_HALBERD = REGISTRY.register("copper_halberd", () -> new CopperHalberdItem());
	public static final RegistryObject<Item> COPPER_GLAIVE = REGISTRY.register("copper_glaive", () -> new CopperGlaiveItem());
	public static final RegistryObject<Item> COPPER_LONGSWORD = REGISTRY.register("copper_longsword", () -> new CopperLongswordItem());
	public static final RegistryObject<Item> COPPER_SPEAR = REGISTRY.register("copper_spear", () -> new CopperSpearItem());
	public static final RegistryObject<Item> COPPER_LANCE = REGISTRY.register("copper_lance", () -> new CopperLanceItem());
	public static final RegistryObject<Item> COPPER_SCYTHE = REGISTRY.register("copper_scythe", () -> new CopperScytheItem());
	public static final RegistryObject<Item> COPPER_PIKE = REGISTRY.register("copper_pike", () -> new CopperPikeItem());
	public static final RegistryObject<Item> COPPER_GREATSWORD = REGISTRY.register("copper_greatsword", () -> new CopperGreatswordItem());
	public static final RegistryObject<Item> COPPER_EXECUTIONER_SWORD = REGISTRY.register("copper_executioner_sword", () -> new CopperExecutionerSwordItem());
	public static final RegistryObject<Item> COPPER_TWIN_BLADE = REGISTRY.register("copper_twin_blade", () -> new CopperTwinBladeItem());
	public static final RegistryObject<Item> COPPER_JAVELIN = REGISTRY.register("copper_javelin", () -> new CopperJavelinItem());
	public static final RegistryObject<Item> COPPER_QUARTERSTAFF = REGISTRY.register("copper_quarterstaff", () -> new CopperQuarterstaffItem());
	public static final RegistryObject<Item> COPPER_ODACHI = REGISTRY.register("copper_odachi", () -> new CopperOdachiItem());
	public static final RegistryObject<Item> COPPER_BOW = REGISTRY.register("copper_bow", () -> new CopperBowItem());

	// Start of user code block custom items
	// End of user code block custom items
	@SubscribeEvent
	public static void clientLoad(FMLClientSetupEvent event) {
		event.enqueueWork(() -> {
			ItemProperties.register(DIAMOND_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(NETHERITE_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(EXPLOSIVE_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(BUCKLER.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(SPIKED_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(ENDER_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(LIVING_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(ASSAULT_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(IRON_BOW.get(), new ResourceLocation("mortius_weaponry_redux:iron_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) IronBowPropertyValueProviderProcedure.execute(entity));
			ItemProperties.register(DIAMOND_BOW.get(), new ResourceLocation("mortius_weaponry_redux:diamond_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) DiamondBowPropertyProcedure.execute(entity));
			ItemProperties.register(NETHERITE_BOW.get(), new ResourceLocation("mortius_weaponry_redux:netherite_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) NetheriteBowPropertyProcedure.execute(entity));
			ItemProperties.register(AUTO_BOW.get(), new ResourceLocation("mortius_weaponry_redux:auto_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) AutoBowPropertyProcedure.execute(entity));
			ItemProperties.register(DIAMOND_BUCKLER.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(QUIVER.get(), new ResourceLocation("mortius_weaponry_redux:quiver_quiver_full"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) QuiverPropertyValueProviderProcedure.execute(itemStackToRender));
			ItemProperties.register(ORNATE_QUIVER.get(), new ResourceLocation("mortius_weaponry_redux:ornate_quiver_quiver_full"),
					(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) QuiverPropertyValueProviderProcedure.execute(itemStackToRender));
			ItemProperties.register(NETHERITE_QUIVER.get(), new ResourceLocation("mortius_weaponry_redux:netherite_quiver_quiver_full"),
					(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) QuiverPropertyValueProviderProcedure.execute(itemStackToRender));
			ItemProperties.register(MUSKET_BALL_POUCH.get(), new ResourceLocation("mortius_weaponry_redux:musket_ball_pouch_quiver_full"),
					(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) QuiverPropertyValueProviderProcedure.execute(itemStackToRender));
			ItemProperties.register(SEALED_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(COPPER_BOW.get(), new ResourceLocation("mortius_weaponry_redux:copper_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) CopperBowPropertyProcedure.execute(entity));
		});
	}
}
